Added ability to specify network in config object
Archarithms/bigio-node pull request #4
Opened 2016-09-13 16:07 UTC by kkanzelmeyer

2016-09-18 03:31 UTC, kkanzelmeyer commented
The dependency updates fix the conflicts with versions of node > 4.3.0. I ran the unit tests with node 6.5.0 and they all passed.

2016-09-18 14:00 UTC, andy-trimble commented on bigio/utils.js
> +    getIp: function (cb) {
The indent of this function is only two spaces, while the rest of the file is four. Please either increase to four, or decrease the rest of the file to two spaces to maintain consistency.

2016-09-18 14:04 UTC, andy-trimble requested changes
Just a formatting change requested, looks good otherwise.

2016-09-18 19:38 UTC, kkanzelmeyer commented on bigio/utils.js
> +    getIp: function (cb) {
done, thanks!

2016-09-18 19:39 UTC, kkanzelmeyer commented
To maintain project consistency I used four spaces for the indentation. Thanks!

2016-09-19 15:12 UTC, andy-trimble approved these changes

2016-09-19 15:13 UTC, merged